export const data = [
	{
		cover: { uri: "https://files.nsctotal.com.br/s3fs-public/graphql-upload-files/festival-danca-joinville_3.jpg?_r.2Hx3E4zg9IeReCRCe_MyBJs3osjzD" },
		title: "Festival de Dança 2022",
		local: "Centreventos Cau Hansen",
		address: "Av. José Vieira, 315 - América",
		date: new Date("2022/07/19"),
		startTime: "20:00",
		endTime: "22:00",
		description: "Uma breve descrição do evento clicado anteriormente pelo usuário.",
		cordinate: { latitude: -26.3051, longitude: -48.8461 },
		category: "música",
		city: "Joinville"
	},
	{
		cover: { uri: "https://cafeviagem.com/wp-content/uploads/2019/05/vinicolas-em-Santa-Catarina-d3.jpg" },
		title: "Degustação de vinhos",
		local: "Vinícola D'alture",
		address: "Rodovia SC 114",
		date: new Date("2022/07/20"),
		startTime: "07:30",
		endTime: "09:00",
		description: "Uma breve descrição do evento clicado anteriormente pelo usuário.",
		cordinate: { latitude: -26.2900, longitude: -48.8200 },
		category: "cinema",
		city: "Joinville"
	},
	{
		cover: { uri: "https://cafeviagem.com/wp-content/uploads/2019/05/vinicolas-em-Santa-Catarina-d3.jpg" },
		title: "Ping Pong",
		local: "Centreventos Cau Hansen",
		address: "Av. José Vieira, 315 - América, Joinville - SC, 89204-110",
		date: new Date("2022/07/20"),
		startTime: "07:30",
		endTime: "09:00",
		description: "Campeonato de ping pong ( solo e duplas )",
		cordinate: { latitude: -26.302624641543016, longitude: -48.88064146131631 },
		category: "esporte",
		city: "Joinville"
	},
	{
		cover: { uri: "https://cafeviagem.com/wp-content/uploads/2019/05/vinicolas-em-Santa-Catarina-d3.jpg" },
		title: "Projeto x",
		local: "Casa de eventos - Super Show",
		address: "R. Visc. de Taunay - Atiradores",
		date: new Date("2022/07/20"),
		startTime: "07:30",
		endTime: "09:00",
		description: "Beber até cair ou até desmaiar, vape e narguilé pra fumar, chame seus amigos pra fazer a noite valer a pena, esqueça tudo!",
		cordinate: { latitude: -26.305694, longitude: -48.852750 },
		category: "gastronomia",
		city: "Joinville"
	},
	{
		cover: { uri: "https://cafeviagem.com/wp-content/uploads/2019/05/vinicolas-em-Santa-Catarina-d3.jpg" },
		title: "Futebol",
		local: "Vinícola D'alture",
		address: "Rodovia SC 114",
		date: new Date("2022/07/13"),
		startTime: "07:30",
		endTime: "09:00",
		description: "Bora bater um bola, quem ganhar leva cerveja pra casa!",
		cordinate: { latitude: -26.312975, longitude: -48.847298 },
		category: "esporte",
		city: "Joinville"
	},
	{
		cover: { uri: "https://cafeviagem.com/wp-content/uploads/2019/05/vinicolas-em-Santa-Catarina-d3.jpg" },
		title: "Campeonato de cubo mágico",
		local: "Ágora Tecpark",
		address: "R. Dona Francisca, 8300 - Distrito Industrial, Joinville - SC, 89219-600",
		date: new Date("2022/07/13"),
		startTime: "07:30",
		endTime: "09:00",
		description: "Bora bater um bola, quem ganhar leva cerveja pra casa!",
		cordinate: { latitude: -26.23620510731389, longitude: -48.88261322193677 },
		category: "esporte",
		city: "Joinville"
	},
]